# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.aimdk.protocol.hal.sensors import rs2_camera_pb2 as aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2


class CameraServiceStub(object):
    """*
    @brief Service provided by realsense_camera_module::RealsenseCameraModule module in aimrt_hal
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_camera_info = channel.unary_unary(
                '/aimdk.protocol.CameraService/get_camera_info',
                request_serializer=aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraInfoRequest.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraInfoResponse.FromString,
                )
        self.get_camera_data = channel.unary_unary(
                '/aimdk.protocol.CameraService/get_camera_data',
                request_serializer=aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraDataRequest.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraDataResponse.FromString,
                )


class CameraServiceServicer(object):
    """*
    @brief Service provided by realsense_camera_module::RealsenseCameraModule module in aimrt_hal
    """

    def get_camera_info(self, request, context):
        """*
        @brief Get camera intrinsic parameters received by realsense_camera_module::RealsenseCameraModule.
        @param GetCameraInfoRequest Camera serial number
        @return GetCameraInfoResponse Camera intrinsics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_camera_data(self, request, context):
        """*
        @brief Get camera data received by realsense_camera_module::RealsenseCameraModule, including camera intrinsics, color and depth image information.
        @param GetCameraDataRequest Camera serial number
        @return GetCameraDataResponse Detailed data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_camera_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_camera_info,
                    request_deserializer=aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraInfoRequest.FromString,
                    response_serializer=aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraInfoResponse.SerializeToString,
            ),
            'get_camera_data': grpc.unary_unary_rpc_method_handler(
                    servicer.get_camera_data,
                    request_deserializer=aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraDataRequest.FromString,
                    response_serializer=aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aimdk.protocol.CameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CameraService(object):
    """*
    @brief Service provided by realsense_camera_module::RealsenseCameraModule module in aimrt_hal
    """

    @staticmethod
    def get_camera_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.CameraService/get_camera_info',
            aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraInfoRequest.SerializeToString,
            aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_camera_data(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.CameraService/get_camera_data',
            aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraDataRequest.SerializeToString,
            aimdk_dot_protocol_dot_hal_dot_sensors_dot_rs2__camera__pb2.GetCameraDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
