# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.aimdk.protocol.sim import sim_observation_service_pb2 as aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2


class SimObservationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_observation = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/get_observation',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetObservationReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetObservationRsp.FromString,
                )
        self.reset = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/reset',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ResetReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ResetRsp.FromString,
                )
        self.attach_obj = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/attach_obj',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AttachReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AttachRsp.FromString,
                )
        self.detach_obj = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/detach_obj',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.DetachReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.DetachRsp.FromString,
                )
        self.task_status = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/task_status',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.TaskStatusReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.TaskStatusRsp.FromString,
                )
        self.exit = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/exit',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ExitReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ExitRsp.FromString,
                )
        self.init_robot = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/init_robot',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitRobotReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitRobotRsp.FromString,
                )
        self.add_camera = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/add_camera',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AddCameraReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AddCameraRsp.FromString,
                )
        self.set_object_pose = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/set_object_pose',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetObjectPoseReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetObjectPoseRsp.FromString,
                )
        self.set_trajectory_list = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/set_trajectory_list',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTrajectoryListReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTrajectoryListRsp.FromString,
                )
        self.set_frame_state = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/set_frame_state',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetFrameStateReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetFrameStateRsp.FromString,
                )
        self.set_task_metric = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/set_task_metric',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTaskMetricReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTaskMetricRsp.FromString,
                )
        self.set_material = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/set_material',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetMaterailReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetMaterialRsp.FromString,
                )
        self.set_light = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/set_light',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetLightReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetLightRsp.FromString,
                )
        self.remove_objs_from_obstacle = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/remove_objs_from_obstacle',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.RemoveObstacleReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.RemoveObstacleRsp.FromString,
                )
        self.store_current_state = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/store_current_state',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.StoreCurrentStateReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.StoreCurrentStateRsp.FromString,
                )
        self.playback = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/playback',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.PlaybackReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.PlaybackRsp.FromString,
                )
        self.get_checker_status = channel.unary_unary(
                '/aimdk.protocol.SimObservationService/get_checker_status',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetCheckerStatusReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetCheckerStatusRsp.FromString,
                )


class SimObservationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_observation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def attach_obj(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def detach_obj(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def task_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def exit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def init_robot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_camera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_object_pose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_trajectory_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_frame_state(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_task_metric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_material(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_light(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remove_objs_from_obstacle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def store_current_state(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def playback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_checker_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimObservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_observation': grpc.unary_unary_rpc_method_handler(
                    servicer.get_observation,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetObservationReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetObservationRsp.SerializeToString,
            ),
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ResetReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ResetRsp.SerializeToString,
            ),
            'attach_obj': grpc.unary_unary_rpc_method_handler(
                    servicer.attach_obj,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AttachReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AttachRsp.SerializeToString,
            ),
            'detach_obj': grpc.unary_unary_rpc_method_handler(
                    servicer.detach_obj,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.DetachReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.DetachRsp.SerializeToString,
            ),
            'task_status': grpc.unary_unary_rpc_method_handler(
                    servicer.task_status,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.TaskStatusReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.TaskStatusRsp.SerializeToString,
            ),
            'exit': grpc.unary_unary_rpc_method_handler(
                    servicer.exit,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ExitReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ExitRsp.SerializeToString,
            ),
            'init_robot': grpc.unary_unary_rpc_method_handler(
                    servicer.init_robot,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitRobotReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitRobotRsp.SerializeToString,
            ),
            'add_camera': grpc.unary_unary_rpc_method_handler(
                    servicer.add_camera,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AddCameraReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AddCameraRsp.SerializeToString,
            ),
            'set_object_pose': grpc.unary_unary_rpc_method_handler(
                    servicer.set_object_pose,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetObjectPoseReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetObjectPoseRsp.SerializeToString,
            ),
            'set_trajectory_list': grpc.unary_unary_rpc_method_handler(
                    servicer.set_trajectory_list,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTrajectoryListReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTrajectoryListRsp.SerializeToString,
            ),
            'set_frame_state': grpc.unary_unary_rpc_method_handler(
                    servicer.set_frame_state,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetFrameStateReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetFrameStateRsp.SerializeToString,
            ),
            'set_task_metric': grpc.unary_unary_rpc_method_handler(
                    servicer.set_task_metric,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTaskMetricReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTaskMetricRsp.SerializeToString,
            ),
            'set_material': grpc.unary_unary_rpc_method_handler(
                    servicer.set_material,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetMaterailReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetMaterialRsp.SerializeToString,
            ),
            'set_light': grpc.unary_unary_rpc_method_handler(
                    servicer.set_light,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetLightReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetLightRsp.SerializeToString,
            ),
            'remove_objs_from_obstacle': grpc.unary_unary_rpc_method_handler(
                    servicer.remove_objs_from_obstacle,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.RemoveObstacleReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.RemoveObstacleRsp.SerializeToString,
            ),
            'store_current_state': grpc.unary_unary_rpc_method_handler(
                    servicer.store_current_state,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.StoreCurrentStateReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.StoreCurrentStateRsp.SerializeToString,
            ),
            'playback': grpc.unary_unary_rpc_method_handler(
                    servicer.playback,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.PlaybackReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.PlaybackRsp.SerializeToString,
            ),
            'get_checker_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_checker_status,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetCheckerStatusReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetCheckerStatusRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aimdk.protocol.SimObservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimObservationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_observation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/get_observation',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetObservationReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetObservationRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/reset',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ResetReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ResetRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def attach_obj(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/attach_obj',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AttachReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AttachRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def detach_obj(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/detach_obj',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.DetachReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.DetachRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def task_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/task_status',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.TaskStatusReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.TaskStatusRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def exit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/exit',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ExitReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.ExitRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def init_robot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/init_robot',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitRobotReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitRobotRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_camera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/add_camera',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AddCameraReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.AddCameraRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_object_pose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/set_object_pose',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetObjectPoseReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetObjectPoseRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_trajectory_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/set_trajectory_list',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTrajectoryListReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTrajectoryListRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_frame_state(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/set_frame_state',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetFrameStateReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetFrameStateRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_task_metric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/set_task_metric',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTaskMetricReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetTaskMetricRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_material(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/set_material',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetMaterailReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetMaterialRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_light(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/set_light',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetLightReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.SetLightRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def remove_objs_from_obstacle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/remove_objs_from_obstacle',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.RemoveObstacleReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.RemoveObstacleRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def store_current_state(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/store_current_state',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.StoreCurrentStateReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.StoreCurrentStateRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def playback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/playback',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.PlaybackReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.PlaybackRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_checker_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimObservationService/get_checker_status',
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetCheckerStatusReq.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__observation__service__pb2.GetCheckerStatusRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
