# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.aimdk.protocol.sim import sim_camera_service_pb2 as aimdk_dot_protocol_dot_sim_dot_sim__camera__service__pb2


class SimCameraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_semantic_data = channel.unary_unary(
                '/aimdk.protocol.SimCameraService/get_semantic_data',
                request_serializer=aimdk_dot_protocol_dot_sim_dot_sim__camera__service__pb2.GetSemanticRequest.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__camera__service__pb2.GetSemanticResponse.FromString,
                )


class SimCameraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_semantic_data(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimCameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_semantic_data': grpc.unary_unary_rpc_method_handler(
                    servicer.get_semantic_data,
                    request_deserializer=aimdk_dot_protocol_dot_sim_dot_sim__camera__service__pb2.GetSemanticRequest.FromString,
                    response_serializer=aimdk_dot_protocol_dot_sim_dot_sim__camera__service__pb2.GetSemanticResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aimdk.protocol.SimCameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimCameraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_semantic_data(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.SimCameraService/get_semantic_data',
            aimdk_dot_protocol_dot_sim_dot_sim__camera__service__pb2.GetSemanticRequest.SerializeToString,
            aimdk_dot_protocol_dot_sim_dot_sim__camera__service__pb2.GetSemanticResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
