launcher:
  physics:
    engine: genie_sim_engine
    engines:
      genie_sim_engine:
        package: genie_sim_engine
        executable: genie_sim_engine_isaacsim.py
        name: genie_sim_engine
    industrial_bridge: ""
  renders: ["render_ovrtx"]
render_ovrtx:
  ros__parameters:
    plugin:
      - genie_sim_render/RosImagePublisherPlugin
