# Default initial positions for genie's ros2_control fake system

initial_positions:
  idx01_body_joint1: 0
  idx02_body_joint2: 0
  idx03_body_joint3: 0
  idx04_body_joint4: 0
  idx05_body_joint5: 0
  idx11_head_joint1: 0
  idx12_head_joint2: 0
  idx13_head_joint3: 0
  idx21_arm_l_joint1: 0
  idx22_arm_l_joint2: 0
  idx23_arm_l_joint3: 0
  idx24_arm_l_joint4: 0
  idx25_arm_l_joint5: 0
  idx26_arm_l_joint6: 0
  idx27_arm_l_joint7: 0
  idx31_gripper_l_inner_joint1: 0
  idx61_arm_r_joint1: 0
  idx62_arm_r_joint2: 0
  idx63_arm_r_joint3: 0
  idx64_arm_r_joint4: 0
  idx65_arm_r_joint5: 0
  idx66_arm_r_joint6: 0
  idx67_arm_r_joint7: 0
  idx71_gripper_r_inner_joint1: 0
