app:
  physics_step: 60
  enable_rate_limit: true
  enable_ros: false
benchmark:
  task_name: market_00_g2
  sub_task_name: stock_and_straighten_shelf
  seed: 1
  model_arc: pi
  num_episode: 1
  record: false
