app:
  physics_step: 60
  rendering_step: 60
  enable_ros: true
  record_img: true
  record_video: true
  enable_playback: true
  enable_pub_depth_camera: true
benchmark:
  task_name: "table_task_g1"
  sub_task_name: "pick_block_color"
  model_arc: ""
layout:
  seed: 1
