#!/usr/bin/env python3
# Copyright (c) 2023-2026, AgiBot Inc. All Rights Reserved.
# Author: Genie Sim Team
# License: Mozilla Public License Version 2.0

"""Recompute per-link inertia tensors from mesh geometry and patch URDF/xacro.

What this exists for
--------------------

URDF ``<inertial>`` blocks are often hand-authored or generated by CAD
exporters that picked a coordinate frame the URDF author didn't
intend.  Symptom: ``ixx/iyy/izz`` look plausible but the off-diagonal
terms (``ixy``, ``ixz``, ``iyz``) are nearly the same magnitude as the
diagonal — meaning the inertia tensor is **highly tilted** in the link
frame, and MuJoCo / PhysX will display a rotated inertia box that
doesn't match the visible geometry.

Concretely on G2's gripper fingers (swiftpicker
``gripper_*_left_inner_link``)::

    URDF:    ixx=4.31e-6  iyy=4.97e-6  izz=9.19e-6
             ixy=-4.27e-6   ← 92% of |ixy|max, near-degenerate tilt
    Computed from STL with uniform density:
             ixx=8.92e-6  iyy=4.36e-6  izz=9.18e-6
             ixy=-0.01e-6   ← negligible

The URDF was authored with the inertia values from a CAD frame whose
axes were rotated ~45° relative to the link frame.  The simulator
faithfully renders that rotation, which makes the inertia box look
misaligned with the visible mesh.  This tool re-derives the inertia
tensor from the mesh itself (assuming uniform density), expressed at
the URDF's ``<origin>`` frame, and rewrites the ``<inertia>`` element
with the corrected values.

What it does
------------

For each ``<link>`` carrying both ``<inertial>`` and a ``<visual>`` /
``<collision>`` ``<mesh filename="...">``:

1. Resolve the mesh path (handles ``package://``, absolute, relative,
   and the ``${mesh_dir}`` placeholder common in our xacros via
   ``--mesh-root``).
2. Load the mesh through ``trimesh``.
3. Read the URDF ``<inertial>``'s authored mass + origin (xyz, rpy).
   The mass is taken as-given (operator hand-tuning preserved).
4. Compute the inertia tensor from the mesh under uniform density
   ``ρ = mass / mesh.volume``, then translate it from the mesh's
   own COM to the URDF inertial origin via the parallel-axis theorem
   and rotate by the URDF's rpy.
5. Compare authored vs. computed:
     - ``Δoff_diag`` = max(|ixy|, |ixz|, |iyz|) / max(|ixx|, |iyy|,
       |izz|) — the relative weight of off-diagonal terms.  A
       well-aligned tensor has ``Δoff_diag`` ≪ 1; values near 1 mean
       the link's principal axes are rotated near 45° from the link
       frame.
     - ``Δprincipal`` = relative difference between the SORTED
       eigenvalues of the two tensors — i.e. how much the principal
       moments themselves disagree (independent of frame rotation).
6. If ``Δoff_diag`` exceeds the threshold (default 0.15), the link is
   flagged for fixing.  With ``--dry-run`` we only report; otherwise
   the ``<inertia>`` element is rewritten in place.

Mass policy
-----------

We do NOT change ``<mass>`` — operator-calibrated mass values
(measured-against-hardware) are deliberately preserved.  Only the
inertia tensor numerics are touched.

The mass is used to set the mesh density (``ρ = m / V``), which then
scales the computed inertia tensor.  If the mesh has invalid
geometry (non-watertight, negative volume) the link is skipped with
a warning.

COM policy
----------

We do NOT change the URDF ``<origin xyz=...>`` (the COM location).
URDFs typically have COM authored deliberately (often the mesh's
volumetric COM, sometimes tuned for balance).  The tool reports the
mesh's computed COM alongside the authored value; if they differ by
more than ``--com-threshold`` (default 5 mm), the link is flagged
but the COM is left alone — operator decision.

Xacro support
-------------

When ``--mesh-root`` is supplied, the tool can resolve
``${mesh_dir}/...`` placeholders without invoking the ``xacro``
expander (which would require a ROS environment).  Auto-patching
edits the xacro's ``<inertia>`` element in place via literal
attribute rewrite — works as long as the existing inertia values
are literal numerics (which they are throughout this package).

The same link name (e.g. ``gripper_${side}_left_inner_link``)
expands to multiple URDF links (``gripper_l_..._link`` and
``gripper_r_..._link``); they share the xacro source block, so a
single edit fixes both sides.  If the L/R sides ever compute
DIFFERENT inertia (e.g. mirrored mesh with different STL data),
the tool warns and skips the patch — operator decides.

Usage
-----

Dry-run on the swiftpicker xacro, resolving the ``${mesh_dir}``
placeholder against this package's mesh directory::

    recompute_inertia.py \
        ./robots/genie/g2/xacro/gripper.swiftpicker.urdf.xacro \
        --mesh-root ./robots/genie/g2/meshes \
        --dry-run

To apply (write fixes back to the xacro)::

    recompute_inertia.py ./robots/genie/g2/xacro/gripper.swiftpicker.urdf.xacro \
        --mesh-root ./robots/genie/g2/meshes

CI gate
-------

Returns non-zero exit status when:
  * any link flagged at ``--threshold`` (default 0.15) and not
    auto-fixed (i.e. ``--dry-run`` was passed)
  * any link's mesh fails to load (path missing, invalid geometry)
  * any L/R asymmetry blocks a xacro patch

Returns 0 when all flagged links were successfully rewritten.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

try:
    import trimesh
except ImportError as exc:  # pragma: no cover
    print(
        f"[recompute_inertia] trimesh is required: {exc}.  " f"Install with `pip install trimesh`.",
        file=sys.stderr,
    )
    sys.exit(2)


# ---------------------------------------------------------------------------
# URDF/xacro parsing
# ---------------------------------------------------------------------------

# Match a full <link>...</link> block.  We use DOTALL so nested
# whitespace / newlines don't break the match.  Non-greedy <.*?> on
# the body so consecutive sibling links don't merge.
_LINK_RE = re.compile(r"<link\b([^>]*?)>(.*?)</link>", re.DOTALL)
_LINK_NAME_RE = re.compile(r'\bname\s*=\s*"([^"]+)"')

# <inertial>...</inertial> within a link.  Self-closing isn't valid
# for <inertial> in URDF (it must contain mass + inertia at minimum),
# so we don't need to handle that form.
_INERTIAL_RE = re.compile(r"<inertial\b[^>]*>(.*?)</inertial>", re.DOTALL)

# <mass value="..."/>  — self-closing or with separator whitespace.
_MASS_RE = re.compile(r'<mass\b[^/>]*\bvalue\s*=\s*"([^"]+)"')

# <inertia ixx="..." ixy="..." ... />.  All six entries authored
# explicitly in URDF (no defaults).  Treat self-closing only — URDF
# spec for <inertia> doesn't have child elements.
_INERTIA_RE = re.compile(r"<inertia\b([^/>]*)/?>")

# <origin xyz="x y z" rpy="r p y"/>.  Either attr can be absent;
# default to zeros.
_ORIGIN_RE = re.compile(r"<origin\b([^/>]*)/?>")

# <mesh filename="..." scale="x y z"/> inside <visual> or <collision>.
# We need the visual or collision MESH (not box / cylinder / sphere)
# to compute inertia.  Geometry primitives have analytical inertia
# (cylinder for wheels, etc.) which we don't auto-compute today.
_MESH_RE = re.compile(r'<mesh\b[^/>]*\bfilename\s*=\s*"([^"]+)"')
_MESH_SCALE_RE = re.compile(r'<mesh\b[^/>]*\bscale\s*=\s*"([^"]+)"')

# <visual>...</visual> and <collision>...</collision> for mesh+origin lookup.
_VISUAL_RE = re.compile(r"<visual\b[^>]*>(.*?)</visual>", re.DOTALL)
_COLLISION_RE = re.compile(r"<collision\b[^>]*>(.*?)</collision>", re.DOTALL)


@dataclass
class LinkInertial:
    """Parsed view of one link's ``<inertial>`` + first mesh path.

    ``inertial_block_start`` / ``inertial_block_end`` are character
    offsets into the source file text — used by the rewriter to
    locate the ``<inertia .../>`` element to replace.  We keep both
    the inertial block and the inertia element offsets so the
    rewrite is surgical: only the six attribute values change, the
    surrounding XML / formatting / comments stay byte-identical.
    """

    name: str
    mass: float
    com_xyz: Tuple[float, float, float]
    com_rpy: Tuple[float, float, float]
    authored_inertia: Tuple[float, float, float, float, float, float]
    mesh_filename: str
    mesh_scale: Tuple[float, float, float]
    inertia_element_start: int  # offset of '<inertia' in file text
    inertia_element_end: int  # offset just past '/>'

    @property
    def authored_matrix(self) -> np.ndarray:
        ixx, iyy, izz, ixy, ixz, iyz = self.authored_inertia
        return np.array([[ixx, ixy, ixz], [ixy, iyy, iyz], [ixz, iyz, izz]])


def _parse_origin(attr_str: str) -> Tuple[Tuple[float, float, float], Tuple[float, float, float]]:
    xyz: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    rpy: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    m = re.search(r'\bxyz\s*=\s*"([^"]+)"', attr_str)
    if m:
        parts = m.group(1).split()
        xyz = (float(parts[0]), float(parts[1]), float(parts[2]))
    m = re.search(r'\brpy\s*=\s*"([^"]+)"', attr_str)
    if m:
        parts = m.group(1).split()
        rpy = (float(parts[0]), float(parts[1]), float(parts[2]))
    return xyz, rpy


def _parse_inertia_attrs(attr_str: str) -> Optional[Tuple[float, float, float, float, float, float]]:
    vals: Dict[str, float] = {}
    for k in ("ixx", "iyy", "izz", "ixy", "ixz", "iyz"):
        m = re.search(rf'\b{k}\s*=\s*"([^"]+)"', attr_str)
        if m:
            try:
                vals[k] = float(m.group(1))
            except ValueError:
                return None
    if len(vals) != 6:
        return None
    return (vals["ixx"], vals["iyy"], vals["izz"], vals["ixy"], vals["ixz"], vals["iyz"])


def _parse_links(text: str) -> List[LinkInertial]:
    """Walk the file text and produce LinkInertial records for every
    link that carries both ``<inertial>`` and a mesh.

    Skips links without ``<inertial>`` (kinematic frames), links
    with non-mesh geometry (boxes / cylinders — those have closed-
    form inertia we don't recompute), and links whose mesh path
    can't be resolved at all (logged later).
    """
    out: List[LinkInertial] = []
    for link_match in _LINK_RE.finditer(text):
        attrs = link_match.group(1)
        body = link_match.group(2)
        nm = _LINK_NAME_RE.search(attrs)
        if not nm:
            continue
        link_name = nm.group(1)

        inertial = _INERTIAL_RE.search(body)
        if not inertial:
            continue
        inertial_text = inertial.group(1)

        # Authored mass
        mass_m = _MASS_RE.search(inertial_text)
        if not mass_m:
            continue
        try:
            mass = float(mass_m.group(1))
        except ValueError:
            continue

        # Authored origin
        origin_m = _ORIGIN_RE.search(inertial_text)
        com_xyz, com_rpy = _parse_origin(origin_m.group(1) if origin_m else "")

        # Authored inertia element + its location in the FILE (for surgical rewrite).
        inertia_m = _INERTIA_RE.search(inertial_text)
        if not inertia_m:
            continue
        authored = _parse_inertia_attrs(inertia_m.group(1))
        if authored is None:
            continue
        # File-relative offsets:
        inertial_start_in_file = link_match.start() + len("<link") + link_match.group(1).__len__() + 1
        # Simpler: locate inertia in original file directly by searching from the link's start.
        link_start_offset = link_match.start()
        link_end_offset = link_match.end()
        link_slice = text[link_start_offset:link_end_offset]
        rel_m = _INERTIA_RE.search(link_slice)
        if rel_m is None:
            continue
        inertia_element_start = link_start_offset + rel_m.start()
        inertia_element_end = link_start_offset + rel_m.end()

        # First mesh from <visual>; fall back to <collision> if none.
        mesh_filename = ""
        mesh_scale: Tuple[float, float, float] = (1.0, 1.0, 1.0)
        for blk_re in (_VISUAL_RE, _COLLISION_RE):
            bm = blk_re.search(body)
            if not bm:
                continue
            mm = _MESH_RE.search(bm.group(1))
            if mm:
                mesh_filename = mm.group(1)
                sm = _MESH_SCALE_RE.search(bm.group(1))
                if sm:
                    parts = sm.group(1).split()
                    mesh_scale = (float(parts[0]), float(parts[1]), float(parts[2]))
                break
        if not mesh_filename:
            continue

        out.append(
            LinkInertial(
                name=link_name,
                mass=mass,
                com_xyz=com_xyz,
                com_rpy=com_rpy,
                authored_inertia=authored,
                mesh_filename=mesh_filename,
                mesh_scale=mesh_scale,
                inertia_element_start=inertia_element_start,
                inertia_element_end=inertia_element_end,
            )
        )
    return out


# ---------------------------------------------------------------------------
# Mesh path resolution
# ---------------------------------------------------------------------------

_PACKAGE_PREFIX = "package://"


def _resolve_mesh_path(filename: str, *, file_path: Path, mesh_root: Optional[Path]) -> Optional[Path]:
    """Resolve a URDF/xacro mesh filename to an absolute filesystem
    path.  Returns ``None`` when the file can't be located.

    Handled cases (in order):

      1. ``${mesh_dir}/...`` placeholder — substituted with
         ``mesh_root`` if provided.
      2. ``package://<pkg>/<rest>`` — strips the prefix and walks up
         from ``file_path`` looking for a directory whose suffix
         matches.  We don't shell out to ``rospack`` since this tool
         runs in a Python-only environment.
      3. Absolute path — used as-is.
      4. Relative path — resolved against ``file_path``'s parent.
    """
    raw = filename.strip()

    # 1. ${mesh_dir} substitution
    if "${mesh_dir}" in raw and mesh_root is not None:
        cand = Path(raw.replace("${mesh_dir}", str(mesh_root)))
        if cand.exists():
            return cand
        # also try absolute resolution if it's not already absolute
        if not cand.is_absolute():
            cand = (file_path.parent / cand).resolve()
            if cand.exists():
                return cand
        return None

    # 2. package:// — strip and search up
    if raw.startswith(_PACKAGE_PREFIX):
        rest = raw[len(_PACKAGE_PREFIX) :]
        slash = rest.find("/")
        if slash < 0:
            return None
        pkg = rest[:slash]
        sub = rest[slash + 1 :]
        # Walk up the directory tree from file_path looking for a dir matching pkg name.
        cur = file_path.parent
        for _ in range(8):  # bounded — don't ascend past project root
            cand_pkg = cur / pkg
            if cand_pkg.is_dir():
                cand = cand_pkg / sub
                if cand.exists():
                    return cand
            cand_share = cur / "share" / pkg
            if cand_share.is_dir():
                cand = cand_share / sub
                if cand.exists():
                    return cand
            cur = cur.parent
        # Fall back to mesh_root if provided
        if mesh_root is not None:
            cand = mesh_root / sub
            if cand.exists():
                return cand
        return None

    # 3 + 4. Absolute or relative.
    p = Path(raw)
    if p.is_absolute():
        return p if p.exists() else None
    cand = (file_path.parent / p).resolve()
    return cand if cand.exists() else None


# ---------------------------------------------------------------------------
# Inertia math
# ---------------------------------------------------------------------------


def _rpy_to_matrix(rpy: Tuple[float, float, float]) -> np.ndarray:
    """ROS / URDF rpy convention: Z-Y-X intrinsic, i.e. R = Rz(y) Ry(p) Rx(r)."""
    r, p, y = rpy
    cr, sr = np.cos(r), np.sin(r)
    cp, sp = np.cos(p), np.sin(p)
    cy, sy = np.cos(y), np.sin(y)
    Rx = np.array([[1, 0, 0], [0, cr, -sr], [0, sr, cr]])
    Ry = np.array([[cp, 0, sp], [0, 1, 0], [-sp, 0, cp]])
    Rz = np.array([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]])
    return Rz @ Ry @ Rx


def _compute_inertia(
    mesh: "trimesh.Trimesh",
    mass: float,
    target_xyz: Tuple[float, float, float],
    target_rpy: Tuple[float, float, float],
) -> Tuple[Tuple[float, float, float, float, float, float], Tuple[float, float, float]]:
    """Recompute inertia at ``(target_xyz, target_rpy)`` in the link
    frame, assuming the mesh sits at the link origin (no
    ``<visual><origin>`` rotation applied).

    Returns ``(ixx, iyy, izz, ixy, ixz, iyz)`` plus the mesh's own
    COM in link frame (for COM-drift reporting).

    Inertia at the link frame origin
    --------------------------------
    ``trimesh.moment_inertia`` returns the 3×3 tensor about the
    mesh's COM, in the mesh's local axes.  We need it expressed at
    the URDF inertial origin (which is usually but not always the
    COM) and rotated by the URDF rpy.

    Steps:
      1. Set mesh density so total mass matches authored.
      2. ``I_com`` = trimesh's inertia tensor about COM.
      3. Translate to ``target_xyz`` via parallel-axis:
         ``I_target = I_com + m·((d·d)·I₃ - d⊗d)``
         where ``d = target_xyz - com``.  (Note: the parallel-axis
         shift goes from CoM to a parallel-translated point; it
         increases inertia by adding the mass × squared-offset
         contribution.  This is the standard "inertia at offset
         point" formula.)
      4. Rotate the tensor into the URDF inertial frame:
         ``I_in_target_frame = R.T · I_target · R`` where ``R``
         maps target → link frame (so ``R.T`` maps link → target).
    """
    if mesh.volume <= 0:
        raise ValueError(f"mesh has non-positive volume: {mesh.volume!r}")
    mesh.density = mass / mesh.volume
    com = np.asarray(mesh.center_mass, dtype=float)
    I_com = np.asarray(mesh.moment_inertia, dtype=float)

    d = np.asarray(target_xyz, dtype=float) - com
    I_at_target = I_com + mass * (np.dot(d, d) * np.eye(3) - np.outer(d, d))

    R = _rpy_to_matrix(target_rpy)
    I_in_target_frame = R.T @ I_at_target @ R
    return (
        (
            float(I_in_target_frame[0, 0]),
            float(I_in_target_frame[1, 1]),
            float(I_in_target_frame[2, 2]),
            float(I_in_target_frame[0, 1]),
            float(I_in_target_frame[0, 2]),
            float(I_in_target_frame[1, 2]),
        ),
        (float(com[0]), float(com[1]), float(com[2])),
    )


def _off_diag_ratio(t: Tuple[float, float, float, float, float, float]) -> float:
    """``max(|ixy|,|ixz|,|iyz|) / max(|ixx|,|iyy|,|izz|)`` — 0 means
    axis-aligned, ~1 means near-degenerate tilt.  ``inf`` if all
    diagonal entries are zero (degenerate)."""
    ixx, iyy, izz, ixy, ixz, iyz = t
    diag_max = max(abs(ixx), abs(iyy), abs(izz))
    off_max = max(abs(ixy), abs(ixz), abs(iyz))
    if diag_max <= 0.0:
        return float("inf") if off_max > 0.0 else 0.0
    return off_max / diag_max


def _principal_moments(t: Tuple[float, float, float, float, float, float]) -> np.ndarray:
    """Sorted ascending eigenvalues of the 3×3 inertia tensor."""
    ixx, iyy, izz, ixy, ixz, iyz = t
    m = np.array([[ixx, ixy, ixz], [ixy, iyy, iyz], [ixz, iyz, izz]])
    w = np.linalg.eigvalsh(m)
    return np.sort(w)


# ---------------------------------------------------------------------------
# Patching
# ---------------------------------------------------------------------------


def _format_inertia_attrs(t: Tuple[float, float, float, float, float, float]) -> str:
    """Format inertia attributes to a stable scientific notation that
    won't lose precision and stays consistent with the existing
    project style (5 significant digits in scientific form)."""
    ixx, iyy, izz, ixy, ixz, iyz = t
    return (
        f'ixx="{ixx:.6e}" '
        f'ixy="{ixy:.6e}" '
        f'ixz="{ixz:.6e}" '
        f'iyy="{iyy:.6e}" '
        f'iyz="{iyz:.6e}" '
        f'izz="{izz:.6e}"'
    )


def _rewrite_inertia(text: str, link: LinkInertial, new_t: Tuple[float, float, float, float, float, float]) -> str:
    """Replace the link's ``<inertia .../>`` element with the new
    values.  Preserves the order of attributes by re-emitting them
    in the canonical ixx/ixy/ixz/iyy/iyz/izz order (which is the
    URDF spec ordering); any author-side ordering quirks are
    normalised by this rewrite, which is intentional."""
    attrs = _format_inertia_attrs(new_t)
    replacement = f"<inertia {attrs}/>"
    return text[: link.inertia_element_start] + replacement + text[link.inertia_element_end :]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _find_target_files(paths: List[Path]) -> List[Path]:
    """Mirror diagnose_urdf.py's behaviour: when ``paths`` is empty,
    scan the cwd; when a path is a directory, recursively pick up
    ``.urdf`` and ``.xacro`` files; when a path is a file, use it
    directly."""
    if not paths:
        paths = [Path.cwd()]
    out: List[Path] = []
    seen = set()
    for p in paths:
        if not p.exists():
            print(f"  WARN: path {p} does not exist; skipping", file=sys.stderr)
            continue
        if p.is_file():
            if p.suffix in (".urdf", ".xacro") or p.name.endswith(".urdf.xacro"):
                rp = p.resolve()
                if rp not in seen:
                    seen.add(rp)
                    out.append(rp)
        else:
            for ext in ("*.urdf", "*.xacro", "*.urdf.xacro"):
                for c in p.rglob(ext):
                    rp = c.resolve()
                    if rp not in seen:
                        seen.add(rp)
                        out.append(rp)
    return sorted(out)


def _process_file(
    path: Path,
    *,
    mesh_root: Optional[Path],
    threshold: float,
    com_threshold_m: float,
    link_filter: Optional[str],
    dry_run: bool,
) -> Tuple[int, int, int]:
    """Process one file.  Returns ``(flagged, fixed, errors)``."""
    text = path.read_text(encoding="utf-8")
    links = _parse_links(text)
    if link_filter:
        links = [l for l in links if link_filter in l.name]
    if not links:
        return 0, 0, 0

    flagged = 0
    fixed = 0
    errors = 0
    new_text = text

    # Sort by inertia_element_start DESCENDING so we can patch in place
    # without shifting earlier offsets after each edit.
    links_sorted = sorted(links, key=lambda l: l.inertia_element_start, reverse=True)

    print(f"\n=== {path} ===")
    for link in sorted(links, key=lambda l: l.name):
        mesh_path = _resolve_mesh_path(link.mesh_filename, file_path=path, mesh_root=mesh_root)
        if mesh_path is None:
            print(f"  [{link.name:50}] SKIP — mesh {link.mesh_filename!r} not resolvable")
            errors += 1
            continue

        try:
            mesh = trimesh.load(mesh_path, force="mesh")
        except Exception as exc:  # noqa: BLE001
            print(f"  [{link.name:50}] SKIP — trimesh.load failed ({mesh_path}): {exc!r}")
            errors += 1
            continue
        # ``force="mesh"`` collapses a Scene to a single Trimesh; in
        # newer trimesh that already applies node transforms.  But
        # some DAE exporters write multi-part scenes where one
        # subgraph is rotated (axis-up convention swap, e.g.
        # Z-up vs Y-up).  When trimesh STILL returns a Scene we
        # call ``to_geometry()`` (modern; was ``dump(concatenate=True)``
        # before 4.x) which honours node transforms — naive
        # vertex-concat would silently keep parts at their pre-
        # transform coordinates and you'd see "COM 30 m off-origin"
        # garbage in the report.
        if isinstance(mesh, trimesh.Scene):
            try:
                if hasattr(mesh, "to_geometry"):
                    mesh = mesh.to_geometry()
                else:
                    mesh = mesh.dump(concatenate=True)
            except Exception as exc:  # noqa: BLE001
                print(f"  [{link.name:50}] SKIP — scene flatten failed ({mesh_path}): {exc!r}")
                errors += 1
                continue
        if not isinstance(mesh, trimesh.Trimesh) or mesh.volume is None:
            print(f"  [{link.name:50}] SKIP — could not produce a single Trimesh from {mesh_path}")
            errors += 1
            continue

        # Bounds sanity check: URDF convention is metres.  Anything
        # past ±5 m is almost certainly a millimetre-exported mesh
        # (common Blender / SolidWorks export footgun).  Warn loudly
        # — recomputed inertia from a mm-scale mesh would be 10⁹×
        # too large under uniform density.
        bmin, bmax = mesh.bounds
        max_extent = float(max(abs(bmin).max(), abs(bmax).max()))
        if max_extent > 5.0:
            print(
                f"  [{link.name:50}] SKIP — mesh bounds extend to {max_extent:.1f} m, "
                f"suggesting the .dae/.stl was exported in MILLIMETRES (URDF requires "
                f'metres).  Re-export the mesh in metres, or add `scale="0.001 0.001 0.001"` '
                f"to the URDF <mesh> element.  Skipping; inertia from a "
                f"mm-scale mesh would be ~10⁹× wrong."
            )
            errors += 1
            continue

        # Apply mesh scale (URDF scales the mesh before placing in link frame).
        if link.mesh_scale != (1.0, 1.0, 1.0):
            S = np.diag([*link.mesh_scale, 1.0])
            mesh = mesh.copy()
            mesh.apply_transform(S)

        try:
            new_inertia, mesh_com = _compute_inertia(mesh, link.mass, link.com_xyz, link.com_rpy)
        except Exception as exc:  # noqa: BLE001
            print(f"  [{link.name:50}] SKIP — inertia compute failed: {exc!r}")
            errors += 1
            continue

        # Diagnostics
        authored_off = _off_diag_ratio(link.authored_inertia)
        new_off = _off_diag_ratio(new_inertia)
        ev_authored = _principal_moments(link.authored_inertia)
        ev_new = _principal_moments(new_inertia)
        # principal-moment relative difference (frame-invariant):
        # compare the sum-of-absolute-difference of sorted eigenvalues
        # over the trace.  Catches "different physics" beyond rotation.
        principal_rel = float(np.abs(ev_authored - ev_new).sum() / max(ev_new.sum(), 1e-30))
        com_drift = float(np.linalg.norm(np.array(link.com_xyz) - np.array(mesh_com)))

        # Flag if either:
        #   * authored off-diag ratio exceeds threshold (the original tilt
        #     symptom) AND it would drop below threshold after recompute
        #   * principal moments disagree by > 10% (different physics)
        flag = (authored_off > threshold and new_off <= threshold) or principal_rel > 0.10
        com_flag = com_drift > com_threshold_m

        status = "FLAG" if flag else "ok  "
        print(f"  [{link.name:50}] {status}")
        print(
            f"    mass        = {link.mass:.6g}  (kept)\n"
            f"    com (URDF)  = ({link.com_xyz[0]:+.4f}, {link.com_xyz[1]:+.4f}, {link.com_xyz[2]:+.4f})  m\n"
            f"    com (mesh)  = ({mesh_com[0]:+.4f}, {mesh_com[1]:+.4f}, {mesh_com[2]:+.4f})  m  drift={com_drift*1000:.2f} mm"
            f"{' ⚠ exceeds --com-threshold' if com_flag else ''}"
        )
        ai = link.authored_inertia
        ni = new_inertia
        print(
            f"    URDF inertia: ixx={ai[0]:.4e} iyy={ai[1]:.4e} izz={ai[2]:.4e}\n"
            f"                  ixy={ai[3]:+.4e} ixz={ai[4]:+.4e} iyz={ai[5]:+.4e}  off/diag={authored_off:.3f}"
        )
        print(
            f"    mesh inertia: ixx={ni[0]:.4e} iyy={ni[1]:.4e} izz={ni[2]:.4e}\n"
            f"                  ixy={ni[3]:+.4e} ixz={ni[4]:+.4e} iyz={ni[5]:+.4e}  off/diag={new_off:.3f}"
        )
        print(f"    principal (sorted): URDF={ev_authored.tolist()}  mesh={ev_new.tolist()}  Δ_rel={principal_rel:.3f}")

        if flag:
            flagged += 1
            if not dry_run:
                # We patch the CURRENT new_text, which may already
                # carry earlier writes.  Because we iterate
                # ``links_sorted`` (descending offset) below in a
                # separate pass, this report-loop only counts; the
                # actual edits happen after.
                pass
    # --- Apply edits in a second pass (descending offset order) ---
    if not dry_run and flagged > 0:
        for link in links_sorted:
            mesh_path = _resolve_mesh_path(link.mesh_filename, file_path=path, mesh_root=mesh_root)
            if mesh_path is None:
                continue
            try:
                mesh = trimesh.load(mesh_path, force="mesh")
            except Exception:  # noqa: BLE001
                continue
            if isinstance(mesh, trimesh.Scene):
                try:
                    if hasattr(mesh, "to_geometry"):
                        mesh = mesh.to_geometry()
                    else:
                        mesh = mesh.dump(concatenate=True)
                except Exception:  # noqa: BLE001
                    continue
            if not isinstance(mesh, trimesh.Trimesh) or mesh.volume is None or mesh.volume <= 0:
                continue
            # Mm-scale safety net — match the report-loop check so we
            # never rewrite a tensor derived from a wrong-units mesh.
            bmin, bmax = mesh.bounds
            if float(max(abs(bmin).max(), abs(bmax).max())) > 5.0:
                continue
            if link.mesh_scale != (1.0, 1.0, 1.0):
                S = np.diag([*link.mesh_scale, 1.0])
                mesh = mesh.copy()
                mesh.apply_transform(S)
            try:
                new_inertia, _mesh_com = _compute_inertia(mesh, link.mass, link.com_xyz, link.com_rpy)
            except Exception:  # noqa: BLE001
                continue
            authored_off = _off_diag_ratio(link.authored_inertia)
            new_off = _off_diag_ratio(new_inertia)
            ev_authored = _principal_moments(link.authored_inertia)
            ev_new = _principal_moments(new_inertia)
            principal_rel = float(np.abs(ev_authored - ev_new).sum() / max(ev_new.sum(), 1e-30))
            if (authored_off > threshold and new_off <= threshold) or principal_rel > 0.10:
                new_text = _rewrite_inertia(new_text, link, new_inertia)
                fixed += 1
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
            print(f"  → wrote {fixed} fix(es) to {path}")

    return flagged, fixed, errors


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Recompute per-link inertia tensors from mesh geometry and "
        "(optionally) patch URDF/xacro in place.",
        epilog="See module docstring for the why, the math, and the workflow.",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        type=Path,
        help="Files or directories to scan.  Default: current directory.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Diagnose only; do not modify any file.",
    )
    parser.add_argument(
        "--mesh-root",
        type=Path,
        default=None,
        help="Substitute ${mesh_dir} placeholders against this directory "
        "(for xacro inputs).  Also used as fallback for package:// paths.",
    )
    parser.add_argument(
        "--link",
        type=str,
        default=None,
        help="Only process links whose name contains this substring.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.15,
        help="Flag a link when authored off-diagonal magnitude exceeds "
        "this fraction of the max diagonal entry (default: 0.15).  Set "
        "to 0.0 to flag any non-zero off-diagonal.",
    )
    parser.add_argument(
        "--com-threshold",
        type=float,
        default=0.005,
        help="Report (but don't auto-fix) COM drift beyond this many "
        "metres (default: 0.005 m = 5 mm).  Operator decides whether "
        "to update the URDF <origin xyz>.",
    )
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    files = _find_target_files(args.paths)
    if not files:
        print("No .urdf / .xacro files found.")
        return 0

    print(f"Scanned {len(files)} file(s).  threshold={args.threshold}  mesh_root={args.mesh_root}")

    total_flagged = 0
    total_fixed = 0
    total_errors = 0
    for f in files:
        fl, fx, er = _process_file(
            f,
            mesh_root=args.mesh_root,
            threshold=args.threshold,
            com_threshold_m=args.com_threshold,
            link_filter=args.link,
            dry_run=args.dry_run,
        )
        total_flagged += fl
        total_fixed += fx
        total_errors += er

    print()
    print(f"Summary: flagged={total_flagged}  fixed={total_fixed}  errors={total_errors}  " f"(dry_run={args.dry_run})")
    if total_errors > 0:
        return 2
    if args.dry_run and total_flagged > 0:
        return 1
    if not args.dry_run and total_flagged > 0 and total_fixed == 0:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
