# -*- coding: utf-8 -*-
# Copyright (c) 2023-2025, AgiBot Inc. All Rights Reserved.
# Author: Genie Sim Team
# License: Mozilla Public License Version 2.0

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/common/se2_velocity.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'aimdk/protocol/common/se2_velocity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import vec2_pb2 as aimdk_dot_protocol_dot_common_dot_vec2__pb2

from aimdk.protocol.common.vec2_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(aimdk/protocol/common/se2_velocity.proto\x12\x0e\x61imdk.protocol\x1a aimdk/protocol/common/vec2.proto\"Z\n\x0bSE2Velocity\x12$\n\x06linear\x18\x01 \x01(\x0b\x32\x14.aimdk.protocol.Vec2\x12%\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x14.aimdk.protocol.Vec2P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.common.se2_velocity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SE2VELOCITY']._serialized_start=94
  _globals['_SE2VELOCITY']._serialized_end=184
# @@protoc_insertion_point(module_scope)
