# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aimdk/protocol/hal/arm/arm.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.aimdk.protocol.common import se3_pose_pb2 as aimdk_dot_protocol_dot_common_dot_se3__pose__pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk_dot_protocol_dot_common_dot_quaternion__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk.protocol.common.quaternion_pb2
try:
  aimdk_dot_protocol_dot_common_dot_rpy__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk_dot_protocol_dot_common_dot_rpy__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_rpy__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk.protocol.common.rpy_pb2

from common.aimdk.protocol.common.se3_pose_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n aimdk/protocol/hal/arm/arm.proto\x12\x0e\x61imdk.protocol\x1a$aimdk/protocol/common/se3_pose.proto\"\'\n\x0cOptionalCond\x12\x17\n\x0f\x65xecutingLineId\x18\x01 \x01(\x05\"\\\n\rLinearMoveExt\x12\x0b\n\x03\x61\x63\x63\x18\x01 \x01(\x01\x12\x0b\n\x03tol\x18\x02 \x01(\x01\x12\x31\n\x0boption_cond\x18\x03 \x01(\x0b\x32\x1c.aimdk.protocol.OptionalCond\"\xb5\x03\n\rLinearMoveReq\x12\x12\n\nrobot_name\x18\x01 \x01(\t\x12(\n\x04pose\x18\x02 \x01(\x0b\x32\x1a.aimdk.protocol.SE3RpyPose\x12&\n\x04mode\x18\x03 \x01(\x0e\x32\x18.aimdk.protocol.MoveMode\x12\x10\n\x08is_block\x18\x04 \x01(\x08\x12\x16\n\x0e\x64istance_frame\x18\x05 \x01(\x01\x12*\n\x03\x65xt\x18\x06 \x01(\x0b\x32\x1d.aimdk.protocol.LinearMoveExt\x12\x18\n\x10\x65\x65_interpolation\x18\x07 \x01(\x08\x12\x13\n\x0bgoal_offset\x18\x08 \x03(\x01\x12\x17\n\x0fpath_constraint\x18\t \x03(\x01\x12+\n#offset_and_constraint_in_goal_frame\x18\n \x01(\x08\x12\x1f\n\x17\x64isable_collision_links\x18\x0b \x03(\t\x12\x18\n\x10motion_run_ratio\x18\x0c \x01(\x01\x12\x1d\n\x15gripper_action_timing\x18\r \x01(\t\x12\x19\n\x11\x66rom_current_pose\x18\x0e \x01(\x08\"0\n\rLinearMoveRsp\x12\x0f\n\x07\x65rrcode\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\t*F\n\x08MoveMode\x12\x10\n\x0cMoveMode_ABS\x10\x00\x12\x11\n\rMoveMode_INCR\x10\x01\x12\x15\n\x11MoveMode_CONTINUE\x10\x02\x32`\n\x11\x41rmControlService\x12K\n\x0blinear_move\x12\x1d.aimdk.protocol.LinearMoveReq\x1a\x1d.aimdk.protocol.LinearMoveRspP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.hal.arm.arm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MOVEMODE']._serialized_start=715
  _globals['_MOVEMODE']._serialized_end=785
  _globals['_OPTIONALCOND']._serialized_start=90
  _globals['_OPTIONALCOND']._serialized_end=129
  _globals['_LINEARMOVEEXT']._serialized_start=131
  _globals['_LINEARMOVEEXT']._serialized_end=223
  _globals['_LINEARMOVEREQ']._serialized_start=226
  _globals['_LINEARMOVEREQ']._serialized_end=663
  _globals['_LINEARMOVERSP']._serialized_start=665
  _globals['_LINEARMOVERSP']._serialized_end=713
  _globals['_ARMCONTROLSERVICE']._serialized_start=787
  _globals['_ARMCONTROLSERVICE']._serialized_end=883
# @@protoc_insertion_point(module_scope)
