# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.aimdk.protocol.hal.arm import arm_pb2 as aimdk_dot_protocol_dot_hal_dot_arm_dot_arm__pb2


class ArmControlServiceStub(object):
    """*
    @brief Service provided by arm control module
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.linear_move = channel.unary_unary(
                '/aimdk.protocol.ArmControlService/linear_move',
                request_serializer=aimdk_dot_protocol_dot_hal_dot_arm_dot_arm__pb2.LinearMoveReq.SerializeToString,
                response_deserializer=aimdk_dot_protocol_dot_hal_dot_arm_dot_arm__pb2.LinearMoveRsp.FromString,
                )


class ArmControlServiceServicer(object):
    """*
    @brief Service provided by arm control module
    """

    def linear_move(self, request, context):
        """*
        @brief Execute linear end-effector motion.
        @param LinearMoveReq
        @return LinearMoveRsp
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArmControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'linear_move': grpc.unary_unary_rpc_method_handler(
                    servicer.linear_move,
                    request_deserializer=aimdk_dot_protocol_dot_hal_dot_arm_dot_arm__pb2.LinearMoveReq.FromString,
                    response_serializer=aimdk_dot_protocol_dot_hal_dot_arm_dot_arm__pb2.LinearMoveRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aimdk.protocol.ArmControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArmControlService(object):
    """*
    @brief Service provided by arm control module
    """

    @staticmethod
    def linear_move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aimdk.protocol.ArmControlService/linear_move',
            aimdk_dot_protocol_dot_hal_dot_arm_dot_arm__pb2.LinearMoveReq.SerializeToString,
            aimdk_dot_protocol_dot_hal_dot_arm_dot_arm__pb2.LinearMoveRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
