app:
  enable_rate_limit: true
  enable_ros: false
benchmark:
  task_name: table_task_2_g2_op
  platform: g2_op
  sub_task_name: sort_number
  seed: 1
  model_arc: corobot
  num_episode: 1
  record: false
