app:
  enable_rate_limit: true
  enable_ros: false
benchmark:
  task_name: sort_fruit_data_collection
  platform: g2_op
  sub_task_name: sort_fruit_data_collection
  seed: 0
  model_arc: corobot
  num_episode: 10

  record: true
