# Copyright (c) 2023-2026, AgiBot Inc. All Rights Reserved.
# Author: Genie Sim Team
# License: Mozilla Public License Version 2.0

INSTRUCTION_TEMPLATE = {
    "pick_billards_color": "{[SIDE]: left/right} arm picks up the {[COLOR]: red/green/blue/..., color of the object in the scene_info} billiard on the table",
    "pick_block_color": "{[SIDE]: left/right} arm picks up the {[COLOR]: red/green/blue/..., color of the object in the scene_info} block on the table",
    "pick_block_shape": "{[SIDE]: left/right} arm picks up the {[SHAPE]: cube/sphere/cylinder/..., shape of the object in the scene_info} block on the table",
    "pick_block_size": "{[SIDE]: left/right} arm picks up the {[SIZE]: smallest/biggest/..., relative size of the object in the scene_info} block on the table",
    "pick_block_number": "{[SIDE]: left/right} arm picks up the building block with number {[NUMBER]: 0/1/2/...} on the table",
    "pick_object_type": "{[SIDE]: left/right} arm picks up the {[TYPE]: fruit/toy/food/beverage/..., type of the object in the scene_info} on the table",
    "pick_pen_color": "{[SIDE]: left/right} arm picks up the {[COLOR]: red/green/blue/..., color of the object in the scene_info} pen on the table",
    "pick_specific_object": "{[SIDE]: left/right} arm picks up the {[SEMANTIC]: pen/cup/fruit/..., semantic of the object in the scene_info} on the table",
    "pick_accessory": "{[SIDE]: left/right} arm picks up the {[SEMANTIC]: bearing rack/hex bolt/..., semantic of the object in the scene_info} on the table",
    "pick_object_position": "{[SIDE]: left/right} arm picks up the object on the table at the {[POSITION]: top left/top center/bottom right/..., position of the object in the scene_info} position",
    "pick_stationery": "{[SIDE]: left/right} arm picks up the {[SEMANTIC]: pen/cup/fruit/..., semantic of the object in the scene_info} on the table",
    "pick_follow_logic_and": "{[SIDE]: left/right} arm picks up the {[DESCRIPTION]: red and circular/xxx and xxx/ ..., description of the object in the scene_info} item on the table",
    "pick_follow_logic_not": "VLM|Picks up the {[DESCRIPTION]: none-xxx, xxx should be replaced with one descriptive term from scene_info of the scene objects} item on the table",
    "pick_follow_logic_or": "VLM|Picks up the {[DESCRIPTION]: A or B, description of the object in the scene_info} item on the table",
    "pick_common_sense": "{[SIDE]: left/right} arm picks up the object that {[COMMON_SENSE]: use common sense description sentences to describe the feature of the object in the scene_info without mentioning name} on the table",
    "place_block_into_box": "{[SIDE]: left/right} arm picks up the {[COLOR]: red/green/blue/..., color of the object in the scene_info} {[SHAPE]: cube/sphere/cylinder/..., shape of the object in the scene_info} block on the table, places it into the {[SHAPE]: cube/sphere/cylinder/..., shape of the object in the scene_info} hole of the building block box",
    "place_object_into_box_position": "{[SIDE]: left/right} arm picks up the {[SEMANTIC]: pen/cup/fruit/..., semantic of the object in the scene_info} on the table, places it into the {[SIDE]: left/right} position of the box",
    "place_object_into_box_color": "{[SIDE]: left/right tag of the apple in scene_info} arm picks up the apple on the table, places it into the {[COLOR]: color of the storage box in scene_info, every color should be used to generate instruction} storage box",
    "place_object_into_box_size": "{[SIDE]: left/right} arm picks up the {[SEMANTIC]: pen/cup/fruit/..., semantic of the object in the scene_info} on the table, places it into the {[SIZE]: smallest/biggest/..., relative size of the object in the scene_info} storage box",
    "sort_accessory": "{[SIDE]: left/right} arm picks up the {[SEMANTIC]: bearing rack/hex bolt/..., semantic of the object in the scene_info} on the table, place it into the corresponding storage bin",
    "straighten_object": "{[SIDE]: left/right} arm picks up the beverage on the table,  straightens the beverage and puts it back in its original position",
    "put_pen_into_penholder": "VLM|{[SIDE]: left/right} arm picks up the pen on the table, insert the pen into the pen holder",
    "push_drawer_color": "{[SIDE]: left/right} arm pushes the {[COLOR]: red/green/blue/..., color of the object in the scene_info} drawer",
    "pull_drawer_number": "{[SIDE]: left/right} arm pulls the drawer with number {[NUMBER]: 0/1/2/..., number of the object in the scene_info}",
    "open_laptop_lid": "{[SIDE]: left/right} arm opens the laptop lid",
    "press_button_color": "{[SIDE]: left/right} arm press the {[COLOR]: red/green/blue/..., color of the object in the scene_info} button",
    "turn_faucet": "{[SIDE]: left/right} arm turns the faucet",
    "bimanual_hold_ball": "VLM|both arm holds the ball",
    "place_object_on_convoy": "{[SIDE]: left/right} arm picks up the object, places it in the box on the conveyor belt",
    "clean_the_desktop": "VLM|clean up the desktop",
    "sort_fruit": "VLM|Sort the fruit into the corresponding box",
    "place_book": "VLM|right arm picks up the book on the table, places it on the shelf",
    "place_book_hard": "VLM|Use both arms to pick up the book on the table, places it on the shelf",
    "open_door": "VLM|Right arm opens the door, push it open",
    "bimanual_hold_ball": "VLM|Both arms hold the ball and lift it up",
    "take_book": "VLM|Right arm takes the book from the shelf, places it in the book holder on the table",
    "empty_desktop_bin": "VLM|Right arm dumps the trash in the trash can on the table into the large trash bin on floor",
    "dump_trash_kitchen": "VLM|Right arm picks up the bowl, dumps the trash into the trash bin on the left side of the table",
    "throw_away_garbage": "VLM|Right arm picks up the garbage on the table, hands over to left arm, and left arm throws it into the trash bin on the left",
    "heat_food": "VLM|heat food in the microwave",
    "hold_pot": "VLM|Both arms hold the pot and place it on the stove",
    "hang_tableware": "VLM|Hang the tableware on the hook",
    "put_utensil_turn_faucet": "VLM|Put the bowl into the sink, turn the faucet on",
    "straighten_object": "VLM|Straighten the {[SEMANTIC]: the semantic_name of beverage in the scene_info} on the table",
    "store_objects_in_drawer": "VLM|Store the object on the table into the drawer",
}
